-- SQL statements for inserting services

USE original_virtual_doctor;

INSERT INTO services (service, cost, hosp_id) VALUES ('Obstetrics', 543.43, 16);
INSERT INTO services (service, cost, hosp_id) VALUES ('Gastroenterology', 734.79, 17);
INSERT INTO services (service, cost, hosp_id) VALUES ('Cardiology', 938.16, 11);
INSERT INTO services (service, cost, hosp_id) VALUES ('Pathology', 805.06, 2);
INSERT INTO services (service, cost, hosp_id) VALUES ('Gastroenterology', 333.0, 6);
INSERT INTO services (service, cost, hosp_id) VALUES ('Dermatology', 714.64, 18);
INSERT INTO services (service, cost, hosp_id) VALUES ('Neurology', 314.29, 2);
INSERT INTO services (service, cost, hosp_id) VALUES ('Pathology', 955.75, 6);
INSERT INTO services (service, cost, hosp_id) VALUES ('Psychiatry', 446.24, 6);
INSERT INTO services (service, cost, hosp_id) VALUES ('Psychiatry', 109.5, 20);
INSERT INTO services (service, cost, hosp_id) VALUES ('Gynecology', 259.01, 2);
INSERT INTO services (service, cost, hosp_id) VALUES ('Gastroenterology', 968.89, 19);
INSERT INTO services (service, cost, hosp_id) VALUES ('Neurology', 791.67, 2);
INSERT INTO services (service, cost, hosp_id) VALUES ('Gynecology', 566.55, 19);
INSERT INTO services (service, cost, hosp_id) VALUES ('Dermatology', 324.96, 3);
INSERT INTO services (service, cost, hosp_id) VALUES ('Gastroenterology', 113.45, 20);
INSERT INTO services (service, cost, hosp_id) VALUES ('Pathology', 321.21, 3);
INSERT INTO services (service, cost, hosp_id) VALUES ('Gastroenterology', 554.27, 16);
INSERT INTO services (service, cost, hosp_id) VALUES ('Neurology', 667.16, 3);
INSERT INTO services (service, cost, hosp_id) VALUES ('Radiology', 773.08, 6);
INSERT INTO services (service, cost, hosp_id) VALUES ('Pathology', 229.41, 10);
INSERT INTO services (service, cost, hosp_id) VALUES ('Orthopedics', 638.93, 20);
INSERT INTO services (service, cost, hosp_id) VALUES ('Dermatology', 695.04, 14);
INSERT INTO services (service, cost, hosp_id) VALUES ('Pathology', 262.6, 7);
INSERT INTO services (service, cost, hosp_id) VALUES ('Obstetrics', 302.2, 9);
INSERT INTO services (service, cost, hosp_id) VALUES ('Neurology', 202.65, 18);
INSERT INTO services (service, cost, hosp_id) VALUES ('Neurology', 679.91, 18);
INSERT INTO services (service, cost, hosp_id) VALUES ('Cardiology', 581.92, 2);
INSERT INTO services (service, cost, hosp_id) VALUES ('Neurology', 710.77, 14);
INSERT INTO services (service, cost, hosp_id) VALUES ('Psychiatry', 289.53, 4);
INSERT INTO services (service, cost, hosp_id) VALUES ('Obstetrics', 138.64, 3);
INSERT INTO services (service, cost, hosp_id) VALUES ('Emergency Care', 572.2, 20);
INSERT INTO services (service, cost, hosp_id) VALUES ('Cardiology', 518.88, 11);
INSERT INTO services (service, cost, hosp_id) VALUES ('Emergency Care', 294.7, 5);
INSERT INTO services (service, cost, hosp_id) VALUES ('Dermatology', 131.15, 11);
INSERT INTO services (service, cost, hosp_id) VALUES ('Obstetrics', 107.48, 16);
INSERT INTO services (service, cost, hosp_id) VALUES ('Gynecology', 896.3, 6);
INSERT INTO services (service, cost, hosp_id) VALUES ('Dermatology', 121.2, 5);
INSERT INTO services (service, cost, hosp_id) VALUES ('Pediatrics', 235.72, 7);
INSERT INTO services (service, cost, hosp_id) VALUES ('Neurology', 230.51, 19);
INSERT INTO services (service, cost, hosp_id) VALUES ('Pediatrics', 817.24, 16);
INSERT INTO services (service, cost, hosp_id) VALUES ('Neurology', 506.75, 13);
INSERT INTO services (service, cost, hosp_id) VALUES ('Pathology', 654.08, 19);
INSERT INTO services (service, cost, hosp_id) VALUES ('Obstetrics', 916.45, 2);
INSERT INTO services (service, cost, hosp_id) VALUES ('Orthopedics', 331.03, 19);
INSERT INTO services (service, cost, hosp_id) VALUES ('Obstetrics', 122.82, 1);
INSERT INTO services (service, cost, hosp_id) VALUES ('Pediatrics', 807.83, 8);
INSERT INTO services (service, cost, hosp_id) VALUES ('Dermatology', 289.54, 17);
INSERT INTO services (service, cost, hosp_id) VALUES ('Psychiatry', 755.68, 16);
INSERT INTO services (service, cost, hosp_id) VALUES ('Gynecology', 158.35, 8);
