"""changed column names

Revision ID: 1d3977f5c007
Revises: 83159cde164f
Create Date: 2024-07-01 02:29:25.470146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d3977f5c007'
down_revision = '83159cde164f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.alter_column('diagnosis',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=2550),
               existing_nullable=True)
        batch_op.alter_column('prescription',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=2550),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.alter_column('prescription',
               existing_type=sa.String(length=2550),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('diagnosis',
               existing_type=sa.String(length=2550),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
