"""changed type of column status

Revision ID: 1d59c6c1272e
Revises: 1d3977f5c007
Create Date: 2024-07-02 01:45:17.115657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d59c6c1272e'
down_revision = '1d3977f5c007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report', sa.String(length=2550), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=25), nullable=True))
        batch_op.drop_column('fully_filled')
        batch_op.drop_column('diagnosis')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnosis', mysql.VARCHAR(length=2550), nullable=True))
        batch_op.add_column(sa.Column('fully_filled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('report')

    # ### end Alembic commands ###
