"""changed the contact column to varchar to accomodate different contact formats

Revision ID: 27dee53c47d1
Revises: 5d95b2d7f3d3
Create Date: 2024-06-19 16:52:08.753046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27dee53c47d1'
down_revision = '5d95b2d7f3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)

    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.String(length=15),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.String(length=15),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.String(length=15),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
