"""removed contact column from staff

Revision ID: 312876a26ae7
Revises: cb6c6f990374
Create Date: 2024-06-24 12:20:33.369481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '312876a26ae7'
down_revision = 'cb6c6f990374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index('contact')
        batch_op.drop_column('contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', mysql.VARCHAR(length=30), nullable=True))
        batch_op.create_index('contact', ['contact'], unique=True)

    # ### end Alembic commands ###
