"""added scheduled time to bookings table

Revision ID: 3a767d2fffae
Revises: 163d90ef895a
Create Date: 2024-06-29 01:44:42.898857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a767d2fffae'
down_revision = '163d90ef895a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('scheduled_time')

    # ### end Alembic commands ###
