"""changed the contact column to varchar to accomodate different contact formats

Revision ID: 52f25bf574c3
Revises: 27dee53c47d1
Create Date: 2024-06-19 16:55:21.982165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52f25bf574c3'
down_revision = '27dee53c47d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=30),
               existing_nullable=True)

    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=30),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
