"""added the column services to bookings table

Revision ID: 5d95b2d7f3d3
Revises: fa2b7777975b
Create Date: 2024-06-17 22:04:50.070277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d95b2d7f3d3'
down_revision = 'fa2b7777975b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('service')

    # ### end Alembic commands ###
