"""added a password column for staff

Revision ID: 83159cde164f
Revises: 3a767d2fffae
Create Date: 2024-06-29 20:46:09.084491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83159cde164f'
down_revision = '3a767d2fffae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
